# 使用 Node.js 镜像构建前端
FROM node:18.18.2 as build

# 设置工作目录
WORKDIR /app

# 复制依赖文件并安装依赖
COPY package*.json ./
RUN npm config set registry https://registry.npmmirror.com/ && npm install

# 复制源代码并构建项目
COPY . .
RUN npm run build  # 构建生产环境的 React 应用

# 使用 Nginx 提供服务
FROM nginx:latest

# 复制 React 构建生成的静态文件到 Nginx 容器的静态文件目录
COPY --from=build /app/build /usr/share/nginx/html

# 将自定义的 nginx 配置文件复制到容器
COPY nginx.conf /etc/nginx/nginx.conf


